<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WhatsApp Bot - KAMAN POS</title>
    <link rel="icon" type="image/png" href="{{ asset('kaman.png') }}">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-100 min-h-screen">


    <main class="max-w-5xl mx-auto px-4 py-8">
        <section class="bg-white rounded-2xl shadow p-6 mb-6">
            <h1 class="text-2xl font-semibold text-slate-900 mb-2">WhatsApp Green API Chatbot</h1>
            <p class="text-slate-600 mb-4">
                This page is for webhook setup and manual testing. The bot reply is generated by AI using your Arabic sales prompt and sent back through Green API.
            </p>

            <div class="bg-emerald-50 border border-emerald-200 rounded-xl p-4">
                <p class="text-sm font-semibold text-emerald-800 mb-1">Webhook URL for Green API</p>
                <code class="block text-xs md:text-sm break-all text-emerald-900">{{ $webhookUrl }}</code>
            </div>
            <div class="mt-4 flex items-center gap-3">
                <button id="toggleWebhookBtn" type="button" class="text-sm px-4 py-2 rounded-lg {{ $webhookActive ? 'bg-rose-600 hover:bg-rose-700 text-white' : 'bg-emerald-600 hover:bg-emerald-700 text-white' }}">
                    {{ $webhookActive ? 'Deactivate Webhook' : 'Activate Webhook' }}
                </button>
                <span id="webhookActiveBadge" class="text-xs px-2 py-1 rounded-full {{ $webhookActive ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-700' }}">
                    {{ $webhookActive ? 'Active' : 'Inactive' }}
                </span>
            </div>
        </section>

        <section class="bg-white rounded-2xl shadow p-6">
            <h2 class="text-lg font-semibold text-slate-900 mb-4">Manual test send</h2>

            <form method="POST" action="{{ route('whatsapp.bot.test-send') }}" class="space-y-4">
                @csrf
                <div>
                    <label for="chat_id" class="block text-sm font-medium text-slate-700 mb-1">chatId (example: 9725XXXXXXX@c.us)</label>
                    <input id="chat_id" name="chat_id" type="text" required class="w-full rounded-lg border border-slate-300 px-3 py-2" value="{{ old('chat_id') }}">
                </div>
                <div>
                    <label for="message" class="block text-sm font-medium text-slate-700 mb-1">Incoming lead message</label>
                    <textarea id="message" name="message" rows="4" required class="w-full rounded-lg border border-slate-300 px-3 py-2">{{ old('message') }}</textarea>
                </div>
                <button type="submit" class="inline-flex items-center rounded-lg bg-emerald-600 text-white px-4 py-2 font-medium hover:bg-emerald-700">
                    Generate Reply and Send
                </button>
            </form>

            @if($errors->any())
                <div class="mt-4 rounded-lg border border-rose-200 bg-rose-50 p-3 text-rose-800 text-sm">
                    {{ $errors->first() }}
                </div>
            @endif

            @if(!empty($lastResult))
                <div class="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-4">
                    <p class="text-sm font-semibold text-slate-900 mb-3">Last test result</p>
                    <div class="space-y-2 text-sm text-slate-700">
                        <p><strong>chatId:</strong> {{ $lastResult['chat_id'] ?? '' }}</p>
                        <p><strong>Incoming:</strong> {{ $lastResult['incoming'] ?? '' }}</p>
                        <p><strong>Reply:</strong> {{ $lastResult['reply'] ?? '' }}</p>
                        <p><strong>Green API status:</strong> {{ $lastResult['green_api_status'] ?? '' }}</p>
                    </div>
                </div>
            @endif
        </section>

        <section class="bg-white rounded-2xl shadow p-6 mt-6">
            <div class="flex items-center justify-between mb-3">
                <h2 class="text-lg font-semibold text-slate-900">Chatbot Prompt</h2>
                <span id="promptSaveStatus" class="text-xs px-2 py-1 rounded-full bg-slate-100 text-slate-600">Not saved</span>
            </div>
            <p class="text-sm text-slate-500 mb-3">
                Customize the AI system prompt used for WhatsApp responses.
            </p>
            <textarea
                id="chatbotPromptInput"
                class="w-full min-h-[220px] rounded-lg border border-slate-300 px-3 py-2 text-sm font-mono"
            >{{ $chatbotPrompt }}</textarea>
            <div class="mt-3 flex items-center gap-2">
                <button id="savePromptBtn" type="button" class="text-sm px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white">
                    Save Prompt
                </button>
                <button id="resetPromptBtn" type="button" class="text-sm px-4 py-2 rounded-lg bg-slate-700 hover:bg-slate-800 text-white">
                    Reset to Default
                </button>
            </div>
        </section>

        <section class="bg-white rounded-2xl shadow p-6 mt-6">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-lg font-semibold text-slate-900">Live webhook activity</h2>
                <div class="flex items-center gap-2">
                    <button id="clearWebhookEventsBtn" type="button" class="text-xs px-3 py-1.5 rounded-lg bg-slate-800 text-white hover:bg-slate-900">
                        Clear events
                    </button>
                    <span id="webhookLiveStatus" class="text-xs px-2 py-1 rounded-full bg-emerald-100 text-emerald-700">Live</span>
                </div>
            </div>

            <div class="grid md:grid-cols-3 gap-3 mb-4">
                <div class="rounded-lg border border-slate-200 bg-slate-50 p-3">
                    <p class="text-xs text-slate-500">Total events</p>
                    <p id="webhookTotalEvents" class="text-xl font-semibold text-slate-900">0</p>
                </div>
                <div class="rounded-lg border border-slate-200 bg-slate-50 p-3">
                    <p class="text-xs text-slate-500">Last update</p>
                    <p id="webhookLastUpdate" class="text-sm font-medium text-slate-900">-</p>
                </div>
                <div class="rounded-lg border border-slate-200 bg-slate-50 p-3">
                    <p class="text-xs text-slate-500">Polling interval</p>
                    <p class="text-sm font-medium text-slate-900">Every 3 seconds</p>
                </div>
            </div>

            <div id="webhookEvents" class="space-y-3 max-h-[460px] overflow-y-auto pr-1">
                <div class="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">
                    Waiting for webhook events...
                </div>
            </div>
        </section>
    </main>

    <script>
        (function () {
            const eventsContainer = document.getElementById('webhookEvents');
            const totalEventsElement = document.getElementById('webhookTotalEvents');
            const lastUpdateElement = document.getElementById('webhookLastUpdate');
            const liveStatusElement = document.getElementById('webhookLiveStatus');
            const clearEventsButton = document.getElementById('clearWebhookEventsBtn');
            const toggleWebhookButton = document.getElementById('toggleWebhookBtn');
            const webhookActiveBadge = document.getElementById('webhookActiveBadge');
            const promptInput = document.getElementById('chatbotPromptInput');
            const savePromptButton = document.getElementById('savePromptBtn');
            const resetPromptButton = document.getElementById('resetPromptBtn');
            const promptSaveStatus = document.getElementById('promptSaveStatus');
            const eventsUrl = "{{ route('whatsapp.bot.events') }}";
            const clearEventsUrl = "{{ route('whatsapp.bot.events.clear') }}";
            const savePromptUrl = "{{ route('whatsapp.bot.prompt.save') }}";
            const resetPromptUrl = "{{ route('whatsapp.bot.prompt.reset') }}";
            const toggleWebhookUrl = "{{ route('whatsapp.bot.toggle') }}";
            const csrfToken = "{{ csrf_token() }}";

            function escapeHtml(value) {
                return String(value ?? '')
                    .replace(/&/g, '&amp;')
                    .replace(/</g, '&lt;')
                    .replace(/>/g, '&gt;')
                    .replace(/"/g, '&quot;')
                    .replace(/'/g, '&#039;');
            }

            function statusBadge(status) {
                if (status === 'processed') {
                    return '<span class="text-xs px-2 py-1 rounded-full bg-emerald-100 text-emerald-700">processed</span>';
                }
                if (status === 'failed') {
                    return '<span class="text-xs px-2 py-1 rounded-full bg-rose-100 text-rose-700">failed</span>';
                }
                if (status === 'fallback') {
                    return '<span class="text-xs px-2 py-1 rounded-full bg-amber-100 text-amber-700">fallback</span>';
                }
                if (status === 'deactivated') {
                    return '<span class="text-xs px-2 py-1 rounded-full bg-slate-200 text-slate-700">deactivated</span>';
                }
                return '<span class="text-xs px-2 py-1 rounded-full bg-amber-100 text-amber-700">ignored</span>';
            }

            function updateWebhookToggleUi(active) {
                webhookActiveBadge.textContent = active ? 'Active' : 'Inactive';
                webhookActiveBadge.className = active
                    ? 'text-xs px-2 py-1 rounded-full bg-emerald-100 text-emerald-700'
                    : 'text-xs px-2 py-1 rounded-full bg-slate-200 text-slate-700';

                toggleWebhookButton.textContent = active ? 'Deactivate Webhook' : 'Activate Webhook';
                toggleWebhookButton.className = active
                    ? 'text-sm px-4 py-2 rounded-lg bg-rose-600 hover:bg-rose-700 text-white'
                    : 'text-sm px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white';
            }

            function renderEvents(events) {
                if (!events.length) {
                    eventsContainer.innerHTML = `
                        <div class="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">
                            Waiting for webhook events...
                        </div>
                    `;
                    return;
                }

                const html = events.slice().reverse().map((event) => `
                    <div class="rounded-lg border border-slate-200 bg-white p-4">
                        <div class="flex items-center justify-between gap-3 mb-2">
                            <p class="text-xs text-slate-500">${escapeHtml(event.time || '-')}</p>
                            ${statusBadge(event.status)}
                        </div>
                        <div class="space-y-1 text-sm text-slate-700">
                            <p><strong>chatId:</strong> ${escapeHtml(event.chat_id || '-')}</p>
                            <p><strong>Incoming:</strong> ${escapeHtml(event.incoming || '-')}</p>
                            <p><strong>Reply:</strong> ${escapeHtml(event.reply || '-')}</p>
                            <p><strong>Green API status:</strong> ${escapeHtml(event.green_api_status ?? '-')}</p>
                            ${event.reason ? `<p><strong>Reason:</strong> ${escapeHtml(event.reason)}</p>` : ''}
                        </div>
                    </div>
                `).join('');

                eventsContainer.innerHTML = html;
            }

            async function loadEvents() {
                try {
                    const response = await fetch(eventsUrl, { headers: { 'Accept': 'application/json' } });
                    if (!response.ok) {
                        throw new Error('Failed to load events');
                    }

                    const data = await response.json();
                    const events = Array.isArray(data.events) ? data.events : [];

                    totalEventsElement.textContent = String(data.count ?? events.length);
                    lastUpdateElement.textContent = new Date().toLocaleTimeString();
                    liveStatusElement.textContent = 'Live';
                    liveStatusElement.className = 'text-xs px-2 py-1 rounded-full bg-emerald-100 text-emerald-700';
                    updateWebhookToggleUi(Boolean(data.webhook_active));
                    renderEvents(events);
                } catch (error) {
                    liveStatusElement.textContent = 'Disconnected';
                    liveStatusElement.className = 'text-xs px-2 py-1 rounded-full bg-rose-100 text-rose-700';
                }
            }

            loadEvents();
            setInterval(loadEvents, 3000);

            savePromptButton.addEventListener('click', async function () {
                savePromptButton.disabled = true;
                promptSaveStatus.textContent = 'Saving...';
                promptSaveStatus.className = 'text-xs px-2 py-1 rounded-full bg-amber-100 text-amber-700';
                try {
                    const response = await fetch(savePromptUrl, {
                        method: 'POST',
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json',
                            'X-CSRF-TOKEN': csrfToken,
                        },
                        body: JSON.stringify({ prompt: promptInput.value }),
                    });
                    if (!response.ok) {
                        throw new Error('Failed to save prompt');
                    }
                    promptSaveStatus.textContent = 'Saved';
                    promptSaveStatus.className = 'text-xs px-2 py-1 rounded-full bg-emerald-100 text-emerald-700';
                } catch (error) {
                    console.error(error);
                    promptSaveStatus.textContent = 'Save failed';
                    promptSaveStatus.className = 'text-xs px-2 py-1 rounded-full bg-rose-100 text-rose-700';
                } finally {
                    savePromptButton.disabled = false;
                }
            });

            resetPromptButton.addEventListener('click', async function () {
                resetPromptButton.disabled = true;
                try {
                    const response = await fetch(resetPromptUrl, {
                        method: 'POST',
                        headers: {
                            'Accept': 'application/json',
                            'X-CSRF-TOKEN': csrfToken,
                        },
                    });
                    if (!response.ok) {
                        throw new Error('Failed to reset prompt');
                    }
                    const data = await response.json();
                    if (typeof data.prompt === 'string') {
                        promptInput.value = data.prompt;
                    }
                    promptSaveStatus.textContent = 'Reset to default';
                    promptSaveStatus.className = 'text-xs px-2 py-1 rounded-full bg-slate-100 text-slate-700';
                } catch (error) {
                    console.error(error);
                    promptSaveStatus.textContent = 'Reset failed';
                    promptSaveStatus.className = 'text-xs px-2 py-1 rounded-full bg-rose-100 text-rose-700';
                } finally {
                    resetPromptButton.disabled = false;
                }
            });

            clearEventsButton.addEventListener('click', async function () {
                clearEventsButton.disabled = true;
                try {
                    const response = await fetch(clearEventsUrl, {
                        method: 'POST',
                        headers: {
                            'Accept': 'application/json',
                            'X-CSRF-TOKEN': csrfToken,
                        },
                    });
                    if (!response.ok) {
                        throw new Error('Failed to clear events');
                    }
                    await loadEvents();
                } catch (error) {
                    console.error(error);
                } finally {
                    clearEventsButton.disabled = false;
                }
            });

            toggleWebhookButton.addEventListener('click', async function () {
                toggleWebhookButton.disabled = true;
                try {
                    const response = await fetch(toggleWebhookUrl, {
                        method: 'POST',
                        headers: {
                            'Accept': 'application/json',
                            'X-CSRF-TOKEN': csrfToken,
                        },
                    });
                    if (!response.ok) {
                        throw new Error('Failed to toggle webhook');
                    }
                    const data = await response.json();
                    updateWebhookToggleUi(Boolean(data.webhook_active));
                    await loadEvents();
                } catch (error) {
                    console.error(error);
                } finally {
                    toggleWebhookButton.disabled = false;
                }
            });
        })();
    </script>
</body>
</html>

